# Generated by Django 4.2.7 on 2024-05-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UserNum", models.IntegerField(default=0)),
                ("NoteNum", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("avatar", models.CharField(max_length=100)),
                ("UserID", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
