# Generated by Django 4.2.7 on 2024-05-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                ("note_id", models.CharField(default="0", max_length=5)),
                (
                    "content_id",
                    models.CharField(
                        default="0", max_length=5, primary_key=True, serialize=False
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("type", models.CharField(max_length=20)),
                ("content", models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_num", models.IntegerField(default=0)),
                ("note_num", models.IntegerField(default=0)),
                ("content_num", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("title", models.CharField(max_length=100)),
                ("user_id", models.CharField(default="0", max_length=5)),
                (
                    "note_id",
                    models.CharField(
                        default="0", max_length=5, primary_key=True, serialize=False
                    ),
                ),
                ("content_num", models.IntegerField(default=0)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("last_edit_time", models.DateTimeField(auto_now=True)),
                ("tags", models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                (
                    "avatar",
                    models.CharField(
                        default="http://10.0.2.2:8000/media/default.png", max_length=100
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        default="0", max_length=5, primary_key=True, serialize=False
                    ),
                ),
                ("auth_id", models.CharField(default="", max_length=20)),
                ("motto", models.CharField(default="My motto is ...", max_length=100)),
            ],
        ),
    ]
