# Generated by Django 4.2.7 on 2024-05-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="UserID",
        ),
        migrations.AddField(
            model_name="user",
            name="auth_id",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="motto",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
