# Generated by Django 4.2.7 on 2024-05-30 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_user_tags_alter_user_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="content",
            new_name="detail",
        ),
    ]
