# Generated by Django 4.2.7 on 2024-05-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_remove_user_userid_user_auth_id_user_motto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                ("title", models.CharField(max_length=100)),
                ("content", models.JSONField(blank=True, default=list, null=True)),
                ("media", models.JSONField(blank=True, default=list, null=True)),
                (
                    "user_id",
                    models.CharField(
                        default="0", max_length=5, primary_key=True, serialize=False
                    ),
                ),
                ("note_id", models.CharField(default="0", max_length=5)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("last_edit_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name="counter",
            old_name="NoteNum",
            new_name="note_num",
        ),
        migrations.RenameField(
            model_name="counter",
            old_name="UserNum",
            new_name="user_num",
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                default="http://10.0.2.2:8000/media/default.png", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default="0", max_length=5, primary_key=True, serialize=False
            ),
        ),
    ]
