# Generated by Django 4.2.7 on 2024-05-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_note_rename_notenum_counter_note_num_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="tags",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="motto",
            field=models.CharField(default="My motto is ...", max_length=100),
        ),
    ]
