# Generated by Django 4.2.7 on 2024-05-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_note_tags_alter_user_motto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                ("note_id", models.CharField(default="0", max_length=5)),
                (
                    "content_id",
                    models.CharField(
                        default="0", max_length=5, primary_key=True, serialize=False
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("type", models.CharField(max_length=20)),
                ("content", models.CharField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name="note",
            name="content",
        ),
        migrations.RemoveField(
            model_name="note",
            name="media",
        ),
        migrations.AddField(
            model_name="counter",
            name="content_num",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="note",
            name="content_num",
            field=models.IntegerField(default=0),
        ),
    ]
